---
- hosts: all
  user: root
  roles:
    - iptables
    - { role: yumrepos, repos: [epel, opennebula]}
    - { role: yumrepos, repos: [epel, opennebula46], when: "one_version == 4.6"}
    - one_core
    - one_sunstone
